// This file is auto-generated by scripts/generate-i18n-locale.ts

import type { Locale } from '@intlify/core-base'

// DONT EDIT THIS FILE MANUALLY
export const currentSupportedLanguages: Locale[] = [
  'en',
  'zh-CN',

  // 'de',
  // 'ja',
  // 'zh-TW',
  // 'zh-HK',
  // 'pt',
  // 'fr',
  // 'ar-DZ',
  // 'ar-SA',
  // 'ar-MA',
  // 'ar-IQ',
  // 'ar-KW',
  // 'ar-TN',
  // 'fi',
  // 'it',
  // 'ru',
  // 'es',
  // 'ko',
  // 'tr',
]

export const currencyMap = {
  'en': 'USD',
  'zh-CN': 'CNY',
}

export const dayjsLocaleImportMap = {
  'en': ['en', () => import('dayjs/locale/en')],
  'zh-CN': ['zh-cn', () => import('dayjs/locale/zh-cn')],
  'ja': ['ja', () => import('dayjs/locale/ja')],
  'ru': ['ru', () => import('dayjs/locale/ru')],
  'fi': ['fi', () => import('dayjs/locale/fi')],
  'it': ['it', () => import('dayjs/locale/it')],
  'ar-DZ': ['ar-dz', () => import('dayjs/locale/ar-dz')],
  'ar-SA': ['ar-sa', () => import('dayjs/locale/ar-sa')],
  'ar-MA': ['ar-ma', () => import('dayjs/locale/ar-ma')],
  'es': ['es', () => import('dayjs/locale/es')],
  'fr': ['fr', () => import('dayjs/locale/fr')],
  'pt': ['pt', () => import('dayjs/locale/pt')],
  'zh-TW': ['zh-tw', () => import('dayjs/locale/zh-tw')],
  'ar-IQ': ['ar-iq', () => import('dayjs/locale/ar-iq')],
  'ar-KW': ['ar-kw', () => import('dayjs/locale/ar-kw')],
  'ar-TN': ['ar-tn', () => import('dayjs/locale/ar-tn')],
  'zh-HK': ['zh-hk', () => import('dayjs/locale/zh-hk')],
  'de': ['de', () => import('dayjs/locale/de')],
  'ko': ['ko', () => import('dayjs/locale/ko')],
  'tr': ['tr', () => import('dayjs/locale/tr')],
}

export const ns = ['app', 'common', 'lang', 'settings', 'shortcuts', 'errors'] as const
export const defaultNS = 'app' as const

export const footerList = [
  {
    title: 'Promo',
    list: [
      {
        name: 'VIP Club',
        url: '',
      },
      {
        name: 'Promotions',
        url: '',
      },
      {
        name: 'Refer and Earn',
        url: '',
      },
      {
        name: 'Bonus',
        url: '',
      },
    ],
  },
  {
    title: 'About Us',
    list: [
      {
        name: 'About AFun',
        url: '',
      },
    ],
  },
  {
    title: 'Help',
    list: [
      {
        name: 'Privacy Policy',
        url: '',
      },
      {
        name: 'AML',
        url: '',
      },
      {
        name: 'Service Terms',
        url: '',
      },
      {
        name: 'Responsible Gambling',
        url: '',
      },
      {
        name: 'FAQ',
        url: '',
      },
    ],
  },
  {
    title: 'Contact Us',
    list: [
      {
        name: 'marketing@afun.com',
        url: '',
      },
      {
        name: 'support@afun.com',
        url: '',
      },
    ],
  },
]

export const joinList = [
  {
    name: 'Instagram',
    url: 'https://web-res-ccc.afunimg8.com/cdn-cgi/image/format=auto/C02/share/instagram.png?20240416',
  },
  {
    name: 'Telegram',
    url: 'https://web-res-ccc.afunimg8.com/cdn-cgi/image/format=auto/C02/share/telegram.png?20240416',
  },
  {
    name: 'Facebook',
    url: 'https://web-res-ccc.afunimg8.com/cdn-cgi/image/format=auto/C02/share/facebook.png?20240416',
  },
  {
    name: 'Whatsapp',
    url: 'https://web-res-ccc.afunimg8.com/cdn-cgi/image/format=auto/C02/share/whatsapp.png?20240416',
  },
  {
    name: 'Twitter',
    url: 'https://web-res-ccc.afunimg8.com/cdn-cgi/image/format=auto/C02/share/twitter.png?20240416',
  },
  {
    name: 'Technology',
    url: 'https://web-res-ccc.afunimg8.com/cdn-cgi/image/format=auto/C02/share/technology.png?20240416',
  },
  {
    name: 'Youtube',
    url: 'https://web-res-ccc.afunimg8.com/cdn-cgi/image/format=auto/C02/share/youtube.png?20240416',
  },
  {
    name: 'Tiktok',
    url: 'https://web-res-ccc.afunimg8.com/cdn-cgi/image/format=auto/C02/share/tiktok.png?20240416',
  },
  {
    name: 'Twitch',
    url: 'https://web-res-ccc.afunimg8.com/cdn-cgi/image/format=auto/C02/share/twitch.png?20240416',
  },
]

export enum ImageLoadStatus {
  Loading = 'loading',
  Loaded = 'loaded',
  Error = 'error',
}
