// This file is auto-generated by scripts/generate-i18n-locale.ts
// DONT EDIT THIS FILE MANUALLY
export const currentSupportedLanguages = [
  'en',
  'de',
  'ja',
  'zh-CN',
  'zh-TW',
  'zh-HK',
  'pt',
  'fr',
  'ar-DZ',
  'ar-SA',
  'ar-MA',
  'ar-IQ',
  'ar-KW',
  'ar-TN',
  'fi',
  'it',
  'ru',
  'es',
  'ko',
  'tr',
]
export const dayjsLocaleImportMap = {
  en: ['en', () => import('dayjs/locale/en')],
}
export const ns = ['app', 'common', 'lang', 'settings', 'shortcuts', 'errors'] as const
export const defaultNS = 'app' as const
